### ISSUE TITLE
"cc.genes.rda" missing

### ISSUE THREAD

**Issue by phantom323** [madhavmantri/chicken_heart#1]
Hi,
   Thank you for this amazing work! I'm trying to reproduce the result, but I can't find the file "cc.genes.rda". Can you please add it?
Best!

**Comment by madhavmantri** [comment]
Hi @phantom323, 

Sorry for the delayed response. I forgot to change the notification settings for this repository.
I have added the "cc.genes.rda" file to the data folder. 

Thank you!
