### ISSUE TITLE
Annotation data for scRNA-seq and spatial data

### ISSUE THREAD

**Issue by HaniJieunKim** [madhavmantri/chicken_heart#2]
Hi! 

Thanks for creating an exciting dataset!

I am wondering if the cell type annotation labels for these datasets can be provided. Apologies if they are already public, I was not able to locate them yet! 

Best regards,

Hani

**Comment by madhavmantri** [comment]
Hi, 

Thank you for your interest in our work. 
The annotations for both scRNAseq and spatial RNAseq data have been added to the meta data files in the data directory of the repository. 

Thanks, 
Madhav
