### ISSUE TITLE
why the result is different？

### ISSUE THREAD

**Issue by wxl-508** [madhavmantri/chicken_heart#3]
![image](https://user-images.githubusercontent.com/101567231/159167405-df8cbd81-5aeb-457f-abe9-702143b0c904.png)

**Comment by wxl-508** [comment]
> ![image](https://user-images.githubusercontent.com/101567231/159167405-df8cbd81-5aeb-457f-abe9-702143b0c904.png)

I use the same code and the data，but the result is different？

**Comment by madhavmantri** [comment]
Hi @wxl-508, 

Thank you for your question. 

Updates in default parameters for some of the preprocessing steps might be causing this issue. Are you using Seurat v-3.2 when trying to reproduce the analysis? Did you apply the exact same preprocessing to the raw dataset and use the scanorama batch correction as implemented in the scRNAseq_scanorama.R script? Can you share these details for me to be able to help?

You can compare your cluster labels to the cluster labels I have included in the [metadata file](https://github.com/madhavmantri/chicken_heart/blob/master/data/scRNAseq_metadata.csv). 

Thanks, 
Madhav

**Comment by wxl-508** [comment]
Hello!  I used the code and data(GSE149457_raw.tar) you provided  and Seurat V3.2, but the result is still different, 


setwd("C:/Users/WXL/Desktop/")
# Load the requisite packages and some additional helper functions.
library(Seurat)###v3.2.0
packageVersion("Seurat")
library(Matrix)
library(stringr)
library(readr)
library(here)
library(fitdistrplus)
library(dplyr)
library(monocle)
library(reticulate)
load(file = "cc.genes.rda")
samples = c("D4", "D7_LV", "D7_RV", "D10_LV", "D10_RV", "D14_LV", "D14_RV")
load("robjs/chicken_raw.Robj")
dim(chicken)
table(chicken$orig.ident)
DefaultAssay(chicken)

# Function to extract expression values for individual datasets
extractRNA_chicken <- function(seurat.object, sample_name){
  return(t(as.matrix(GetAssayData(seurat.object)))[colnames(seurat.object)[seurat.object$orig.ident == sample_name],])
}

# Prepare datasets and gene lists for scanorama integration
data = list(extractRNA_chicken(chicken, samples[1]), extractRNA_chicken(chicken, samples[2]), extractRNA_chicken(chicken, samples[3]), extractRNA_chicken(chicken, samples[4]), extractRNA_chicken(chicken, samples[5]), extractRNA_chicken(chicken, samples[6]), extractRNA_chicken(chicken, samples[7]))
gene_list = list(rownames(chicken), rownames(chicken), rownames(chicken), rownames(chicken), rownames(chicken), rownames(chicken), rownames(chicken))

# Intregration starts here
scanorama = import('scanorama')
integrated.corrected.data = scanorama$correct(data, gene_list, return_dimred=TRUE, return_dense=TRUE, ds_names = samples, verbose = TRUE)

 save(integrated.corrected.data, file="robjs/corrected_SCT_counts_scano.Robj")
load("robjs/corrected_SCT_counts_scano.Robj")

corrected_scanorama <- t(do.call(rbind, integrated.corrected.data[[2]]))

colnames(corrected_scanorama) <- colnames(chicken)
rownames(corrected_scanorama) <- integrated.corrected.data[[3]]
dim(corrected_scanorama)
corrected_scanorama_pca <- t(do.call(rbind, integrated.corrected.data[[1]]))
colnames(corrected_scanorama_pca) <- colnames(chicken)
dim(corrected_scanorama_pca)


# Create assay from integrated values and save to seurat object
scanorama_assay <- CreateAssayObject(data = corrected_scanorama)
chicken[["scanorama"]] <- scanorama_assay
DefaultAssay(chicken) <- "scanorama"

# Preprocess scanorama values and perform PCA
DefaultAssay(chicken)
chicken <- FindVariableFeatures(chicken, assay = "scanorama", selection.method = "vst")
chicken <- ScaleData(chicken)
chicken <- RunPCA(object = chicken, assay = "scanorama", verbose = F, reduction.name = "pca_scanorama")

# Clustering and UMAP reduction on scanorama values
chicken <- FindNeighbors(object=chicken, assay = "scanorama", reduction = "pca_scanorama", dims = 1:20, k.param = 30, force.recalc = TRUE)
chicken <- FindClusters(object=chicken, resolution=0.5)
table(chicken$scanorama_snn_res.0.5)
# This command should give seventeen clusters to replicate the analysis
# table(chicken$scanorama_snn_res.0.5)
 # 0    1    2    3    4    5    6    7    8    9   10   11   12   13   14   15   16 
#3391 3185 2709 2220 2154 1421 1225  970  772  768  746  706  575  480  437  287  269 
 ###the result is different.

**Comment by madhavmantri** [comment]
Hello @wxl-508, 

I suspect if changes in default seed values in some preprocessing step is causing this difference in analysis. I will rerun the scripts to investigate this and get back to you as soon as possible. In the meantime, you can use the [meta data file](https://github.com/madhavmantri/chicken_heart/blob/master/data/scRNAseq_metadata.csv) to label cell types. If you can send me an email at mm2937@cornell.edu, I can also provide you the .Robj file with the processed seurat object for this dataset.

Thanks,
Madhav
