### ISSUE TITLE
Ensembl to gene symbol

### ISSUE THREAD

**Issue by Huimin721** [madhavmantri/chicken_heart#4]
Dear team,

I read the h5 files into R and found the rows of gene expressions are annotated as Ensembl ID instead of the gene symbol. I also searched the gallus symbol in bioMart, but many Ensembls do not have a corresponding symbol. May I ask how you transform the gallus Ensembls into symbols when processing the data? Thanks so much.

**Comment by madhavmantri** [comment]
Hi @Huimin721, 

I used Ensembl genome reference and annotation files while aligning the datasets. When I read the single cell h5 files submitted on GEO using the Read_10X_h5 function in Seurat, the files contain gene names for most genes. For example, the rownames of the Seurat object for day4 post fertilization dataset contains gene names for 13869 out of 24356 total genes, containing majority of experimentally validated protein-coding genes. I directly used these h5 files for all analysis presented in the paper. 

As far as I am aware, Ensembl only maps IDs to gene names for experimentally validated genes from a list of databases. It does not map all gene IDs to names.  

I hope this answers your questions. 
Please let me know if you have additional concerns!

**Comment by Huimin721** [comment]
> Hi @Huimin721,
> 
> I used Ensembl genome reference and annotation files while aligning the datasets. When I read the single cell h5 files submitted on GEO using the Read_10X_h5 function in Seurat, the files contain gene names for most genes. For example, the rownames of the Seurat object for day4 post fertilization dataset contains gene names for 13869 out of 24356 total genes, containing majority of experimentally validated protein-coding genes. I directly used these h5 files for all analysis presented in the paper.
> 
> As far as I am aware, Ensembl only maps IDs to gene names for experimentally validated genes from a list of databases. It does not map all gene IDs to names.
> 
> I hope this answers your questions. Please let me know if you have additional concerns!

Hi @madhavmantri ,

Thanks so much! In this case, I will also focus on genes with symbols.
