### ISSUE TITLE
cell type co-localization/abundance prediction

### ISSUE THREAD

**Issue by skim245** [madhavmantri/chicken_heart#5]
Dear authors, 
thank you for sharing the scripts for reproducibility. 

I have a question on how to reproduce Fig. 1e, "chord diagrams representing cell-type proximity maps"
based on the method section, it seems like top 4 predicted cell types were considered to draw this map and I would like to get more guidance on how to do so. 

Thank you in advance!

**Comment by madhavmantri** [comment]
Hello @skim245, 

Thank you for your question.

Yes. As mentioned in the methods sections of the manuscript. The top four predicted cell types (top 4 cell types with the highest deconvolution score for every spot)  were used to estimate a cell type pair colocalization matrix for every spatial dataset. 
We implemented a brute force method to count these pairs and save them in cell type colocalization abundance matrices for every dataset and then plot it on chord diagrams. The code to generate the matrices and for plotting is available in the script: https://github.com/madhavmantri/chicken_heart/blob/master/scripts/anchor_integeration.R script under the section to calulcate celltype pairs neighborhood maps.

I hope this helps. 

Thank you. 
Madhav
