### ISSUE TITLE
Questions for annotation

### ISSUE THREAD

**Issue by Huimin721** [madhavmantri/chicken_heart#6]
Dear team,

Thank you for sharing the data. I'm looking into your region annotations and have a question. I didn't see atrioventricular mesenchyme in your annotations. Do you think it is reasonable to annotate the region you annotated as 'valves' as a mixture of atrioventricular mesenchyme and valves? Thanks so much.

**Comment by madhavmantri** [comment]
Hi @Huimin721, 

Yes. you are correct. 

1. In the spatial transcriptomics data from day 4, the hearts contain atrioventricular mesenchyme cushion which contains cells that will go through the process of EMT and extension/elongation to form valves in a chambered heart. 
2. In the scRNAseq data, we removed valve tissue for day 7, 10, and 14 but the  day 4 dataset includes valve or atrioventricular mesenchyme cushion cells as it was not possible for us to collect only ventricular tissue from day 4 hearts. 

Both these population were labelled as valve cells as exploring the heterogeneity of cell states within these cells was outside the scope of the study where we wanted to study EMT changes in populations from ventricular wall. 

You can easily subset the cells/spots annotated as valves and explore the heterogeneity or composition of those transcriptomes.  

I hope this clarifies your query.

Thank you!
Madhav

**Comment by Huimin721** [comment]
> Hi @Huimin721,
> 
> Yes. you are correct.
> 
> 1. In the spatial transcriptomics data from day 4, the hearts contain atrioventricular mesenchyme cushion which contains cells that will go through the process of EMT and extension/elongation to form valves in a chambered heart.
> 2. In the scRNAseq data, we removed valve tissue for day 7, 10, and 14 but the  day 4 dataset includes valve or atrioventricular mesenchyme cushion cells as it was not possible for us to collect only ventricular tissue from day 4 hearts.
> 
> Both these population were labelled as valve cells as exploring the heterogeneity of cell states within these cells was outside the scope of the study where we wanted to study EMT changes in populations from ventricular wall.
> 
> You can easily subset the cells/spots annotated as valves and explore the heterogeneity or composition of those transcriptomes.
> 
> I hope this clarifies your query.
> 
> Thank you! Madhav

Yes, this clarified my questions. Thanks so much!
