### ISSUE TITLE
Missing obs_names in tissue Positions.txt file

### ISSUE THREAD

**Issue by ajitashree** [madhavmantri/chicken_heart#7]
Dear Madhav,

The obs_names corresponding to chicken heart Anndata are missing in the tissue_positions.txt file. Furthermore, there is a mismatch in the no of indices in the data and txt file. The tissue position file only has 4992 spots whereas the anndata file has the following no of spots.

1. D4: 5653 
2. D7: 8457 
3. D10:3004
4. D14: 5181

Can you please help with this issue?

**Comment by madhavmantri** [comment]
Hi @ajitashree, 

the tissue_position files are generated using the space ranger count command to be used as an input for Seurat. Tissue position files have H&E image coordinates and information about the presence/absence of the tissue for every spot barcode (~5000 total barcodes) on the capture area. 

The anndata object sizes that you shared do not match the objects for visium datasets. The H5 files for spatial RNAseq datasets only contain D4: 474 spots, D7: 1966 spots, D10: 1916 spots, D14: 1967 spots. 

Are you sure you are reading the correct H5 files. Can you share the names of the files and the code you use to read them for me to help?

Best, 
Madhav

**Comment by ajitashree** [comment]
Thanks @madhavmantri for specifying the dimension, I was able to retrieve the right data and use it.
